const cate = [
	{
		"catename":"全て",
		"typename":[],
		"state":false
	},
	{
		"catename":"戦闘機",
		"typename":["艦上戦闘機"],
		"state":false
	},
	{
		"catename":"爆撃機",
		"typename":["艦上爆撃機","噴式戦闘爆撃機"],
		"state":false
	},
	{
		"catename":"攻撃機",
		"typename":["艦上攻撃機"],
		"state":false
	},
	{
		"catename":"艦偵",
		"typename":["艦上偵察機"],
		"state":false
	},
	{
		"catename":"陸戦\r\n陸攻",
		"typename":["陸上攻撃機","局地戦闘機","陸上偵察機"],
		"state":false
	},
	{
		"catename":"小口径",
		"typename":["小口径主砲"],
		"state":true
	},
	{
		"catename":"中口径",
		"typename":["中口径主砲"],
		"state":false
	},
	{
		"catename":"大口径",
		"typename":["大口径主砲"],
		"state":false
	},
	{
		"catename":"副砲",
		"typename":["副砲"],
		"state":false
	},
	{
		"catename":"魚雷",
		"typename":["魚雷","潜水艦魚雷","特殊潜航艇"],
		"state":false
	},
	{
		"catename":"電探",
		"typename":["小型電探","大型電探","潜水艦装備"],
		"state":false
	},
	{
		"catename":"対潜",
		"typename":["爆雷","ソナー","オートジャイロ","対潜哨戒機","大型ソナー"],
		"state":false
	},
	{
		"catename":"強化弾",
		"typename":["対空強化弾","対艦強化弾"],
		"state":false
	},
	{
		"catename":"機銃\r\n高射",
		"typename":["対空機銃","高射装置"],
		"state":false
	},
	{
		"catename":"機関\r\nバルジ",
		"typename":["機関部強化","追加装甲(中型)","追加装甲(大型)"],
		"state":false
	},
	{
		"catename":"探照灯",
		"typename":["探照灯","大型探照灯"],
		"state":false
	},
	{
		"catename":"水偵",
		"typename":["水上偵察機","水上戦闘機"],
		"state":false
	},
	{
		"catename":"瑞雲\r\n回翼",
		"typename":["水上爆撃機"],
		"state":false
	},
	{
		"catename":"大発",
		"typename":["上陸用舟艇","特型内火艇"],
		"state":false
	},
	{
		"catename":"大型飛",
		"typename":["大型飛行艇"],
		"state":false
	},
	{
		"catename":"その他",
		"typename":["対地装備","照明弾","簡易輸送部材","艦艇修理施設","司令部施設","航空要員","水上艦要員","戦闘糧食","補給物資"],
		"state":false
	}
]

export default cate